name: 🐛 不具合報告
description: 不具合・バグの報告はこちら
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: 概要
      description: 不具合の内容を具体的かつ簡潔に記入してください。
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: 重大度
      description: 不具合の重大度はどれくらいですか？
      options:
        - 重大度1：全ユーザーがサービスを利用できない状態
        - 重大度2：大半のユーザーがサービスを利用できない状態
        - 重大度3：一部のユーザーがサービスを利用できない状態
        - 重大度4：サービスの使いやすさに影響するが停止することはない状態
        - 重大度5：サービスの使いやすさにも影響しない状態
      default: 0
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      description: 不具合を再現する手順を記入してください。
      placeholder: |
        1. '...' に移動
        2. '....' をクリック
        3. '....' までスクロール
        4. エラーが発生
  - type: textarea
    id: expected
    attributes:
      label: 期待する動作
      description: 本来どのような動作をするべきですか？
  - type: dropdown
    id: browsers
    attributes:
      label: 不具合が確認されたブラウザ
      multiple: true
      options:
        - Windows Chrome
        - Windows Firefox
        - Mac Chrome
        - Mac Firefox
        - Mac Safari
        - iOS Chrome
        - iOS Safari
        - Android Chrome
        - その他
  - type: textarea
    id: logs
    attributes:
      label: 関連するログ出力
      description: 関連するログ出力をコピー＆ペーストしてください。
      render: bash
  - type: textarea
    id: remarks
    attributes:
      label: 備考・補足
      description: お客様や運用チームへのアナウンス状況など、その他に関連する情報があれば記入してください。
