name: 🔧 リファクタリング
description: コードの改善・リファクタリングについてはこちら
labels: ["refactoring", "technical-debt"]
body:
  - type: textarea
    id: current-state
    attributes:
      label: 現在の状況
      description: リファクタリング対象のコードやシステムの現在の状況を説明してください。
    validations:
      required: true
  - type: dropdown
    id: refactoring-type
    attributes:
      label: リファクタリングの種類
      options:
        - コード構造の改善
        - パフォーマンスの最適化
        - 可読性の向上
        - テストカバレッジの改善
        - 依存関係の整理
        - セキュリティの強化
        - その他
      default: 0
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - 高：すぐに対応が必要
        - 中：近いうちに対応したい
        - 低：時間があるときに対応
      default: 1
    validations:
      required: true
  - type: textarea
    id: improvement-plan
    attributes:
      label: 改善計画
      description: どのようにリファクタリングを行う予定ですか？
  - type: textarea
    id: risks
    attributes:
      label: リスクと対策
      description: リファクタリングに伴うリスクと対策があれば記入してください。
  - type: textarea
    id: remarks
    attributes:
      label: 備考・補足
      description: その他関連する情報があれば記入してください.
